export { default as IconTimer } from './IconTimer.vue'
export { default as IconFast } from './IconFast.vue'
export { default as IconFlower } from './IconFlower.vue'
export { default as IconHeart } from './IconHeart.vue'
export { default as IconArrowLeft } from './IconArrowLeft.vue'
